In [1]:
import pandas as pd

In [12]:
import numpy as np

## Loading the data

In [87]:
a=pd.read_csv('SoFar.csv')

## Creating DataFrame for the data

In [90]:
df = pd.DataFrame(a)

## Analysing Data types and Data Structure

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20300 entries, 0 to 20299
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   patient_id            20300 non-null  object
 1   visit_date            20300 non-null  object
 2   doctor_id             20300 non-null  object
 3   doctor_name           20300 non-null  object
 4   department            20300 non-null  object
 5   admission_type        20300 non-null  object
 6   treatment_type        20300 non-null  object
 7   wait_time_min         17795 non-null  object
 8   treatment_cost        18653 non-null  object
 9   hospital_stay_days    18679 non-null  object
 10  readmission_30d       20300 non-null  object
 11  patient_satisfaction  14542 non-null  float64
 12  doctor_rating         14559 non-null  float64
 13  insurance_claim       20300 non-null  object
 14  revenue_generated     20300 non-null  int64
dtypes: float64(2), int64(1), object(12)
memory usage: 2.3+ MB

In [14]:
df.describe()

       patient_satisfaction  doctor_rating  revenue_generated
count          14542.000000   14559.000000       20300.000000
mean               2.995186       2.971770       14023.124926
std                1.421723       1.413081        6366.131943
min                1.000000       1.000000        3001.000000
25%                2.000000       2.000000        8500.750000
50%                3.000000       3.000000       14065.000000
75%                4.000000       4.000000       19577.500000
max                5.000000       5.000000       25000.000000

In [16]:
df.shape

(20300, 15)

## Checking null values

In [12]:
a=df.isnull().sum()
print(a)

patient_id                 0
visit_date                 0
doctor_id                  0
doctor_name                0
department                 0
admission_type             0
treatment_type             0
wait_time_min           2505
treatment_cost          1647
hospital_stay_days      1621
readmission_30d            0
patient_satisfaction    5758
doctor_rating           5741
insurance_claim            0
revenue_generated          0
dtype: int64

## Checking duplicate values

In [18]:
dup=df.duplicated().sum()
print(dup)

300

In [24]:
print(df.to_string())

      patient_id  visit_date doctor_id doctor_name    department admission_type treatment_type wait_time_min treatment_cost hospital_stay_days readmission_30d  patient_satisfaction  doctor_rating insurance_claim  revenue_generated
0         P00001  2024/03/06      D109   Dr. Brown   Pediatrics         Routine        Surgery            55          19614                  4               1                   5.0            1.0               1              10486
1         P00002  2024-01-17      D107   Dr. Patel   Orthopedics      Emergency     Medication           105          12882                  4           FALSE                   2.0            NaN             Yes               7512
2         P00003  2024-03-31      D117   Dr. Smith     Neurology        Routine     Medication           NaN          19332                NaN               0                   1.0            1.0             Yes              22020
3         P00004  2024/03/28      D119    Dr. Chen    Pediatrics      emergency        Surgery            20          23191                 10           FALSE                   3.0            NaN           FALSE              13192
4         P00005  2024/04/13      D113   Dr. Adams    Cardiology       Referral        surgery            80          22668                 15             Yes                   5.0            3.0           FALSE               6724
5         P00006  2024-02-22      D120   Dr. Brown     Neurology        Routine     Medication           109          24967                  ?               1                   NaN            4.0             Yes              19754
6         P00007  10-04-2024      D117  Dr. Taylor   orthopedics       Referral        therapy            87          13443                  3           FALSE                   2.0            NaN               1              19630
7         P00008  13/04/2024      D118   Dr. Patel     Neurology        ROUTINE        Therapy            97           5684                 12           FALSE                   3.0            NaN             Yes              21272
8         P00009  2024-01-23      D119   Dr. Kumar     Neurology        ROUTINE        therapy            39           4213                 11            TRUE                   3.0            NaN               0               4800
9         P00010  01-02-2024      D117   Dr. Patel     Neurology        Routine     Medication            76           3015                  2             Yes                   NaN            4.0               0              18623
10        P00011  2024-03-07      D103  Dr. Wilson   Orthopedics      Emergency        surgery           110           7114                 15             Yes                   2.0            NaN           FALSE              17416
11        P00012  15-04-2024      D115     Dr. Lee   Pediatrics         Routine        Therapy            28           8806                 11             Yes                   5.0            1.0              No               5085
12        P00013  04/03/2024      D102   Dr. Adams   Orthopedics       Referral     Medication           117           4895                 15            TRUE                   2.0            NaN             Yes              23075
13        P00014  09-04-2024      D100  Dr. Garcia    cardiology        ROUTINE        Surgery           NaN          10622                  8              No                   NaN            3.0              No               8853
14        P00015  28-04-2024      D120   Dr. Kumar    Cardiology       Referral        Surgery            40          13828                 15             Yes                   NaN            4.0              No               4250
15        P00016  19/02/2024      D120  Dr. Wilson   Orthopedics        Routine        Therapy            69          13401                  1           FALSE                   NaN            2.0               1              15520
16        P00017  2024-03-02      D111   Dr. Smith    Cardiology      Emergency     Medication            44           3144                 10           FALSE                   NaN            NaN               1              24703
17        P00018  2024/03/18      D105   Dr. Adams   Pediatrics       Emergency        Therapy           NaN          18693                 13           FALSE                   1.0            3.0              No               8944
18        P00019  2024/03/23      D120  Dr. Taylor    cardiology      emergency    Observation            77          11630                  6               0                   2.0            NaN           FALSE              15183
19        P00020  2024-02-14      D104    Dr. Khan   orthopedics        ROUTINE        therapy            60           4779                 15            TRUE                   5.0            5.0             Yes              17667
20        P00021  2024/04/07      D120    Dr. Khan   Orthopedics      emergency     Medication            72              ?                  1            TRUE                   2.0            5.0           FALSE              18589
21        P00022  01/01/2024      D108   Dr. Brown   Pediatrics        Referral        therapy           NaN          17880                  1           FALSE                   NaN            3.0               1              10152
22        P00023  26/01/2024      D107   Dr. Adams    cardiology        Routine        Therapy            21          14804                 13              No                   2.0            3.0           FALSE              14177
23        P00024  31-01-2024      D104    Dr. Chen    cardiology      emergency    Observation            92           9828                 13              No                   NaN            NaN            TRUE              14282
24        P00025  08/02/2024      D105  Dr. Garcia    Cardiology       Referral        Surgery           104          21500                  7               1                   5.0            NaN             Yes              10923
25        P00026  2024-02-20      D118    Dr. Chen    cardiology        ROUTINE        Surgery            79           3721                  9             Yes                   NaN            2.0             Yes              20300
26        P00027  21-01-2024      D118   Dr. Smith    Cardiology       Referral     Medication             ?          21501                  1              No                   5.0            2.0             Yes              24572
27        P00028  29/03/2024      D113   Dr. Kumar    Pediatrics      emergency        surgery            94          21270                  1               1                   3.0            NaN            TRUE               6254
28        P00029  22-01-2024      D104  Dr. Wilson     Neurology       Referral        Surgery            64            NaN                 10             Yes                   NaN            1.0               1              18669
29        P00030  05/03/2024      D102  Dr. Wilson   Pediatrics       Emergency        surgery            76          23666                  9           FALSE                   3.0            1.0               1              14884
30        P00031  26/04/2024      D106  Dr. Garcia   orthopedics        ROUTINE     Medication            51           5375                 11             Yes                   NaN            1.0            TRUE               8464
31        P00032  10-01-2024      D111   Dr. Patel   orthopedics       Referral        surgery            20           5316                  4               0                   4.0            4.0            TRUE               6418
32        P00033  2024/01/09      D109  Dr. Garcia    cardiology       Referral     Medication            34            NaN                NaN            TRUE                   2.0            4.0             Yes              14260
33        P00034  20/04/2024      D109   Dr. Patel   Pediatrics        Referral        Surgery            65          21432                NaN             Yes                   1.0            3.0               0              11407
34        P00035  2024-01-01      D111    Dr. Chen   Pediatrics         Routine        therapy           NaN          17185                  2               1                   NaN            NaN             Yes              12461
35        P00036  2024/01/14      D110    Dr. Khan    cardiology      emergency     Medication            80           9068                 12               0                   NaN            NaN               1               7018
36        P00037  2024/03/07      D107     Dr. Lee   Pediatrics        Referral    Observation            68          13008                  8               0                   NaN            4.0              No               5971
37        P00038  30/01/2024      D101  Dr. Taylor    Cardiology      Emergency        Therapy            44            NaN                  7               0                   5.0            1.0           FALSE              17164
38        P00039  14-03-2024      D113    Dr. Chen   Pediatrics       Emergency        Surgery           NaN          22264                  3            TRUE                   1.0            5.0               1              14820
39        P00040  2024-01-18      D116   Dr. Adams    cardiology        Routine     Medication            36          19398                  6           FALSE                   3.0            NaN             Yes               6126
40        P00041  03-01-2024      D116  Dr. Wilson     Neurology        ROUTINE        Therapy            48           3868                NaN             Yes                   1.0            NaN           FALSE              14973
41        P00042  08-04-2024      D112    Dr. Khan    cardiology        Routine        therapy            17          12984                 14           FALSE                   1.0            1.0             Yes              13904
42        P00043  2024/03/17      D110  Dr. Garcia     Neurology       Referral    Observation           105           5203                  6               0                   1.0            3.0               1              15857
43        P00044  08-03-2024      D110  Dr. Taylor   Pediatrics       emergency        surgery           NaN          21544                  6           FALSE                   4.0            5.0               0              21826
44        P00045  2024/01/01      D119  Dr. Wilson    Cardiology        ROUTINE        Therapy            87          24675                 11           FALSE                   NaN            2.0           FALSE               5482
45        P00046  2024/01/16      D103   Dr. Adams    Cardiology      Emergency     Medication           102          21443                 11               0                   3.0            1.0               1              14818
46        P00047  2024-02-11      D111  Dr. Garcia    Pediatrics        Routine        therapy            32           9105                  6               1                   1.0            5.0               1              19533
47        P00048  2024-02-25      D100   Dr. Adams   Pediatrics       emergency     Medication           NaN          23768                 14             Yes                   4.0            NaN             Yes              19556
48        P00049  12-04-2024      D106   Dr. Patel    Cardiology        ROUTINE        surgery            35          13480                  9              No                   2.0            3.0             Yes              14207
49        P00050  16-02-2024      D105   Dr. Kumar   orthopedics        ROUTINE     Medication             ?          22367                  6              No                   4.0            2.0              No               8929
50        P00051  2024/02/20      D107    Dr. Khan   orthopedics      Emergency        Surgery           117           7504                  1           FALSE                   5.0            1.0               1              21344
51        P00052  2024/02/11      D111   Dr. Kumar    Cardiology       Referral        therapy            26            NaN                 14               0                   NaN            2.0             Yes              24139
52        P00053  2024/01/29      D110   Dr. Adams   orthopedics        ROUTINE    Observation           100          21924                  4             Yes                   5.0            2.0               0               7890
53        P00054  10-03-2024      D113   Dr. Smith     Neurology      emergency        surgery           119          13590                  7             Yes                   2.0            2.0            TRUE              21014
54        P00055  2024-01-07      D103     Dr. Lee   Pediatrics         Routine     Medication           106          20359                 15              No                   2.0            1.0           FALSE               8433
55        P00056  2024/04/02      D105  Dr. Taylor   Orthopedics        ROUTINE        surgery           110           4023                 11               1                   1.0            4.0           FALSE              20025
56        P00057  2024/02/29      D100    Dr. Khan   orthopedics        ROUTINE    Observation            80          10971                  2           FALSE                   3.0            2.0            TRUE              15257
57        P00058  2024/04/19      D104   Dr. Patel   Pediatrics         Routine        surgery             ?          18514                  5             Yes                   3.0            NaN             Yes               9951
58        P00059  2024-04-05      D119  Dr. Taylor    Cardiology        Routine        Surgery            54           7873                NaN           FALSE                   NaN            NaN            TRUE              11260
59        P00060  25/01/2024      D108   Dr. Kumar   Pediatrics        Referral        Therapy            25          14457                  4              No                   1.0            NaN               0              22981
60        P00061  2024-04-21      D118   Dr. Brown    Cardiology        Routine        therapy            43          23330                  8              No                   4.0            3.0              No              23469
61        P00062  16/02/2024      D111  Dr. Garcia   Pediatrics         Routine     Medication            20          17238                 11               1                   NaN            5.0              No              10114
62        P00063  2024-04-02      D108    Dr. Khan   Pediatrics       emergency        therapy            62          13201                NaN               0                   1.0            NaN               1              18528
63        P00064  2024/02/11      D108     Dr. Lee   Pediatrics       Emergency        Therapy            25          16029                  9               0                   3.0            3.0            TRUE              19116
64        P00065  2024-03-08      D108   Dr. Brown   Pediatrics        Referral        Surgery            18          21125                 10           FALSE                   2.0            4.0           FALSE              14612
65        P00066  27/02/2024      D109    Dr. Chen   Orthopedics        ROUTINE        Surgery            90          17489                 13              No                   NaN            NaN            TRUE               4717
66        P00067  2024/04/04      D119  Dr. Taylor    Cardiology        Routine        Surgery            61          24332                  1             Yes                   NaN            4.0               0               5593
67        P00068  2024-04-30      D111   Dr. Adams    Cardiology      Emergency        therapy            55          21682                 12            TRUE                   4.0            NaN               0              12445
68        P00069  14-01-2024      D109   Dr. Adams    Cardiology        ROUTINE        Surgery            12           7782                NaN             Yes                   NaN            1.0               1               5617
69        P00070  09-02-2024      D115   Dr. Smith    cardiology        Routine        Therapy            68          24240                 12            TRUE                   1.0            NaN             Yes              21058
70        P00071  2024/01/03      D111   Dr. Brown   Pediatrics        Referral     Medication            69          16909                  4               0                   3.0            NaN               0               6063
71        P00072  20-03-2024      D108  Dr. Wilson   Orthopedics      emergency    Observation           109          24646                  8            TRUE                   2.0            2.0               0              19807
72        P00073  2024-02-10      D119     Dr. Lee   orthopedics      Emergency        Therapy            28          22065                  8               0                   NaN            2.0              No              19149
73        P00074  17/03/2024      D114    Dr. Chen    Cardiology        Routine    Observation            35          23593                  ?              No                   2.0            2.0              No              21994
74        P00075  2024/02/20      D120   Dr. Kumar     Neurology       Referral        Therapy            85          21489                 11               1                   5.0            4.0               0               6317
75        P00076  29/04/2024      D115     Dr. Lee   Pediatrics         Routine        therapy            39           9562                  6            TRUE                   1.0            2.0             Yes              19332
76        P00077  2024/02/10      D103   Dr. Kumar    Cardiology      Emergency        Surgery            10          16409                 13            TRUE                   NaN            5.0             Yes               9377
77        P00078  13/04/2024      D114     Dr. Lee    Pediatrics      Emergency    Observation            10           3113                  8              No                   2.0            4.0              No              24257
78        P00079  2024-02-02      D113   Dr. Kumar     Neurology        ROUTINE        Therapy             6           3127                  4              No                   3.0            1.0            TRUE               4690
79        P00080  18-03-2024      D100  Dr. Wilson   Pediatrics         ROUTINE        Surgery           107          24683                 15              No                   2.0            3.0              No              11281
80        P00081  2024-03-04      D111    Dr. Chen   Pediatrics        Referral        Surgery            73          23771                  9              No                   1.0            3.0               1              19398
81        P00082  2024-04-29      D101   Dr. Brown    Cardiology      Emergency        Surgery           NaN          13421                  1             Yes                   3.0            4.0           FALSE              19299
82        P00083  08-02-2024      D100   Dr. Smith   Orthopedics      Emergency        therapy            45           4549                NaN            TRUE                   1.0            2.0            TRUE              20987
83        P00084  24/04/2024      D107  Dr. Garcia    Pediatrics        Routine        surgery            20           9515                  8             Yes                   5.0            NaN             Yes              11808
84        P00085  2024/02/14      D116   Dr. Patel     Neurology       Referral        surgery            13          22061                 11           FALSE                   1.0            2.0               1               3852

# Cleaning Data

### Changing different date formats to same date format

In [115]:
df['visit_date'] = pd.to_datetime(df['visit_date'], format='mixed')

In [116]:
df['visit_date'].head()

0   2024-03-06
1   2024-01-17
2   2024-03-31
3   2024-03-28
4   2024-04-13
Name: visit_date, dtype: datetime64[ns]

## Changing case for words to same case in admission_type column

In [117]:
df[['admission_type','treatment_type']].head()

  admission_type treatment_type
0        Routine        Surgery
1      Emergency     Medication
2        Routine     Medication
3      Emergency        Surgery
4       Referral        Surgery

In [21]:
df['admission_type']=df['admission_type'].str.capitalize()

In [22]:
df['treatment_type']=df['treatment_type'].str.capitalize()

In [118]:
df[['admission_type','treatment_type']].head(10)

  admission_type treatment_type
0        Routine        Surgery
1      Emergency     Medication
2        Routine     Medication
3      Emergency        Surgery
4       Referral        Surgery
5        Routine     Medication
6       Referral        Therapy
7        Routine        Therapy
8        Routine        Therapy
9        Routine     Medication

# Filling null values with median for wait_time_min column

In [41]:
df['wait_time_min'].isnull().sum()

np.int64(2505)

In [10]:
print(df['wait_time_min'].dtype)

object

### As the "wait_time_min" column is in object datatype, im converting that into 'int' datatype to perform fillna() to replace the NaN values with median

In [13]:
df['wait_time_min'] = pd.to_numeric(df['wait_time_min'], errors='coerce').fillna(0).astype(np.int64)

In [28]:
print(df['wait_time_min'].dtype)

float64

In [30]:
df['wait_time_min'].isnull().sum()

np.int64(0)

In [26]:
df['wait_time_min'] = df['wait_time_min'].replace(0, np.nan)

In [29]:
df['wait_time_min'] = df['wait_time_min'].fillna(df['wait_time_min'].mean())

In [39]:
df['wait_time_min'] = df['wait_time_min'].round(2)

### Checking null values in treatment_cost, if so replacing it with mean values

In [45]:
df['treatment_cost'].isnull().sum()

np.int64(1647)

In [46]:
df['treatment_cost'] = pd.to_numeric(df['treatment_cost'], errors='coerce').fillna(0).astype(np.int64)

In [47]:
df['treatment_cost'] = df['treatment_cost'].replace(0, np.nan)

In [48]:
df['treatment_cost'] = df['treatment_cost'].fillna(df['treatment_cost'].mean())

In [119]:
df['treatment_cost'].isnull().sum()

np.int64(0)

### Checking null values in hospital_stay_days, if so replacing it with mean values

In [51]:
df['hospital_stay_days'].isnull().sum()

np.int64(1621)

In [54]:
df['hospital_stay_days'] = pd.to_numeric(df['hospital_stay_days'], errors='coerce').fillna(0).astype(np.int64)

In [55]:
df['hospital_stay_days'] = df['hospital_stay_days'].replace(0, np.nan)

In [56]:
df['hospital_stay_days'] = df['hospital_stay_days'].fillna(df['hospital_stay_days'].mean())

In [57]:
df['hospital_stay_days'].isnull().sum()

np.int64(0)

In [61]:
df['hospital_stay_days'] = df['hospital_stay_days'].round(1)

### Column re-admission has mixture of boolean values, so im changing the values as only to 'Yes' or 'No'

In [64]:
df['readmission_30d'].value_counts()

readmission_30d
0        3413
No       3401
1        3400
FALSE    3390
Yes      3352
TRUE     3344
Name: count, dtype: int64

In [101]:
def fix(x):
    if x in ['1','Yes','TRUE']:
        return 'Yes'
    else:
        return 'No'

In [68]:
df['readmission_30d'] = df['readmission_30d'].apply(fix)

In [69]:
df['readmission_30d'].value_counts()

readmission_30d
No     10204
Yes    10096
Name: count, dtype: int64

In [72]:
df['readmission_30d'].isnull().sum()

np.int64(0)

### Checking null values in patient_satisfaction, if so replacing it with mean values

In [73]:
df['patient_satisfaction'].isnull().sum()

np.int64(5758)

In [74]:
df['patient_satisfaction'] = pd.to_numeric(df['patient_satisfaction'], errors='coerce')

In [75]:
df['patient_satisfaction'].fillna(df['patient_satisfaction'].mean(), inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_17204\1956206649.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['patient_satisfaction'].fillna(df['patient_satisfaction'].mean(), inplace=True)

In [76]:
df['patient_satisfaction']=df['patient_satisfaction'].round(1)

In [78]:
df['patient_satisfaction'].head()

0    5.0
1    2.0
2    1.0
3    3.0
4    5.0
Name: patient_satisfaction, dtype: float64

In [80]:
df['patient_satisfaction'].isna().sum()

np.int64(0)

In [81]:
df.to_csv('SoFar.csv')

In [100]:
df.to_csv('Testing2.csv')

### Checking null values in doctor_rating, if so replacing it with mean values

In [93]:
df['doctor_rating'].isnull().sum()

np.int64(5741)

In [94]:
df['doctor_rating']=pd.to_numeric(df['doctor_rating'], errors= 'coerce')

In [95]:
df['doctor_rating'].fillna(df['doctor_rating'].mean(), inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_17204\541526266.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['doctor_rating'].fillna(df['doctor_rating'].mean(), inplace=True)

In [96]:
df['doctor_rating'].isnull().sum()

np.int64(0)

In [97]:
df['doctor_rating']=df['doctor_rating'].round()

In [98]:
df['doctor_rating']

0        1.0
1        3.0
2        1.0
3        3.0
4        3.0
        ...
20295    3.0
20296    4.0
20297    4.0
20298    2.0
20299    3.0
Name: doctor_rating, Length: 20300, dtype: float64

In [105]:
df.to_csv('SoFar.csv')

### Column insurance_claim has mixture of boolean values, so im changing the values as only to 'Yes' or 'No'

In [102]:
df['insurance_claim'].value_counts()

insurance_claim
0        3451
FALSE    3409
No       3385
TRUE     3376
Yes      3343
1        3336
Name: count, dtype: int64

## Using the fix() function that is already used for re-admission column

In [103]:
df['insurance_claim'] = df['insurance_claim'].apply(fix)

In [104]:
df['insurance_claim'].value_counts()

insurance_claim
No     10245
Yes    10055
Name: count, dtype: int64

## Checking null values in doctor_rating, if so replacing it with mean values

In [106]:
df['revenue_generated'].isnull().sum()

np.int64(0)

In [107]:
df['revenue_generated'].sum()

np.int64(284669436)

# Final Check

In [108]:
df.isnull().sum()

Unnamed: 0              0
patient_id              0
visit_date              0
doctor_id               0
doctor_name             0
department              0
admission_type          0
treatment_type          0
wait_time_min           0
treatment_cost          0
hospital_stay_days      0
readmission_30d         0
patient_satisfaction    0
doctor_rating           0
insurance_claim         0
revenue_generated       0
dtype: int64

In [112]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [120]:
df.to_csv('Final_Cleaned_Hospital_Data.csv',index=False)